#!/bin/bash
# Copy binary/static assets to build/ for external loading

# pdf.js assets
mkdir -p build/cmaps
rsync -av --recursive --exclude='.*' pdf.js/external/bcmaps/ build/cmaps/
rsync -av --recursive --exclude='.*' pdf.js/external/standard_fonts/ build/standard_fonts/
mkdir -p build/wasm
cp pdf.js/external/openjpeg/openjpeg.wasm build/wasm/

# ONNX runtime
mkdir -p build/onnx
cp src/pdf/structure/model/onnx/ort-wasm-simd.wasm build/onnx/

# ML model binaries
mkdir -p build/line-seg
cp src/pdf/structure/model/line-seg/model.onnx build/line-seg/
