export {
	SDT_PACK_VERSION,
	SDT_SCHEMA_VERSION,
} from '../structured-document-text/src/version.js';

// Output versions for SDT generated by document-worker processors.
// Zotero compares these exactly to decide whether an existing SDT cache
// should be regenerated.
export const SDT_PROCESSOR_VERSIONS = Object.freeze({
	pdf: 1,
	epub: 1,
	snapshot: 1,
});
